import 'package:flutter/material.dart';

class LearningContent {
  static final Map<String, List<Map<String, dynamic>>> data = {
    "Poems": [
      {
        "title": "Twinkle Twinkle",
        "sub": "Classic Nursery Rhyme",
        "icon": "⭐",
        "color": Colors.purpleAccent,
        "content": [
          "Twinkle, twinkle, little star,",
          "How I wonder what you are!",
          "Up above the world so high,",
          "Like a diamond in the sky.",
        ],
      },
      {
        "title": "Johnny Johnny",
        "sub": "Funny Rhyme",
        "icon": "🍬",
        "color": Colors.orangeAccent,
        "content": [
          "Johnny Johnny, yes papa?",
          "Eating sugar? No papa.",
          "Telling lies? No papa.",
          "Open your mouth. Ha ha ha!",
        ],
      },
      {
        "title": "Baa Baa Black Sheep",
        "sub": "Animal Rhyme",
        "icon": "🐑",
        "color": Colors.blueAccent,
        "content": [
          "Baa, baa, black sheep,",
          "Have you any wool?",
          "Yes sir, yes sir,",
          "Three bags full.",
        ],
      },
      {
        "title": "Humpty Dumpty",
        "sub": "Story Rhyme",
        "icon": "🥚",
        "color": Colors.redAccent,
        "content": [
          "Humpty Dumpty sat on a wall,",
          "Humpty Dumpty had a great fall,",
          "All the king’s horses and all the king’s men,",
          "Couldn't put Humpty together again.",
        ],
      },
      {
        "title": "Rain Rain Go Away",
        "sub": "Weather Rhyme",
        "icon": "🌧️",
        "color": Colors.teal,
        "content": [
          "Rain rain go away,",
          "Come again another day,",
          "Little children want to play,",
          "Rain rain go away.",
        ],
      },
      {
        "title": "London Bridge",
        "sub": "Action Rhyme",
        "icon": "🌉",
        "color": Colors.indigo,
        "content": [
          "London Bridge is falling down,",
          "Falling down, falling down,",
          "London Bridge is falling down,",
          "My fair lady.",
        ],
      },
      {
        "title": "Chubby Cheeks",
        "sub": "Cute Rhyme",
        "icon": "😊",
        "color": Colors.pinkAccent,
        "content": [
          "Chubby cheeks, dimple chin,",
          "Rosy lips, teeth within,",
          "Curly hair, very fair,",
          "Eyes are blue, lovely too.",
        ],
      },
      {
        "title": "One Two Buckle My Shoe",
        "sub": "Counting Rhyme",
        "icon": "👞",
        "color": Colors.green,
        "content": [
          "One, two, buckle my shoe,",
          "Three, four, shut the door,",
          "Five, six, pick up sticks,",
          "Seven, eight, lay them straight.",
        ],
      },
      {
        "title": "Old MacDonald",
        "sub": "Animal Song",
        "icon": "🐄",
        "color": Colors.brown,
        "content": [
          "Old MacDonald had a farm,",
          "E-I-E-I-O,",
          "And on that farm he had a cow,",
          "E-I-E-I-O.",
        ],
      },
      {
        "title": "Row Row Row Your Boat",
        "sub": "Action Song",
        "icon": "🚣",
        "color": Colors.cyan,
        "content": [
          "Row, row, row your boat,",
          "Gently down the stream,",
          "Merrily, merrily, merrily, merrily,",
          "Life is but a dream.",
        ],
      },
    ],

    "English": [
      {
        "title": "Alphabets (A-Z)",
        "sub": "A for Apple, B for Ball",
        "icon": "🔤",
        "color": Colors.blueAccent,
        "content": [
          "🍎 A for Apple",
          "🎈 B for Ball",
          "🐱 C for Cat",
          "🐕 D for Dog",
          "🐘 E for Elephant",
          "🐟 F for Fish",
          "🦒 G for Giraffe",
          "🏠 H for House",
          "🍦 I for Ice cream",
          "🧃 J for Juice",
          "🪁 K for Kite",
          "🦁 L for Lion",
          "🥭 M for Mango",
          "🪺 N for Nest",
          "🍊 O for Orange",
          "🦜 P for Parrot",
          "👑 Q for Queen",
          "🐇 R for Rabbit",
          "⭐ S for Star",
          "🐯 T for Tiger",
          "☂️ U for Umbrella",
          "🚐 V for Van",
          "⌚ W for Watch",
          "🎄 X for Xmas Tree",
          "🛳️ Y for Yacht",
          "🦓 Z for Zebra",
        ],
      },
      {
        "title": "Action Words",
        "sub": "Move your body!",
        "icon": "🏃",
        "color": Colors.orangeAccent,
        "content": [
          "🏃 Run",
          "🚶 Walk",
          "💃 Dance",
          "😴 Sleep",
          "📚 Read",
          "✍️ Write",
          "🎨 Draw",
          "🏊 Swim",
          "🗣️ Speak",
          "👀 Look",
          "👂 Listen",
          "🍽️ Eat",
        ],
      },
      {
        "title": "Colors",
        "sub": "Learn Basic Colors",
        "icon": "🎨",
        "color": Colors.pinkAccent,
        "content": [
          "🔴 Red",
          "🟢 Green",
          "🔵 Blue",
          "🟡 Yellow",
          "🟠 Orange",
          "🟣 Purple",
          "⚫ Black",
          "⚪ White",
          "🟤 Brown",
          "🌸 Pink",
        ],
      },
      {
        "title": "Shapes",
        "sub": "Basic Shapes",
        "icon": "🔷",
        "color": Colors.teal,
        "content": [
          "⚪ Circle",
          "⬜ Square",
          "🔺 Triangle",
          "🔷 Diamond",
          "⭐ Star",
          "❤️ Heart",
          "⬛ Rectangle",
          "🥚 Oval",
        ],
      },
      {
        "title": "Days of the Week",
        "sub": "7 Days",
        "icon": "📅",
        "color": Colors.deepPurple,
        "content": [
          "Sunday",
          "Monday",
          "Tuesday",
          "Wednesday",
          "Thursday",
          "Friday",
          "Saturday",
        ],
      },
      {
        "title": "Months of the Year",
        "sub": "12 Months",
        "icon": "🗓️",
        "color": Colors.indigo,
        "content": [
          "January",
          "February",
          "March",
          "April",
          "May",
          "June",
          "July",
          "August",
          "September",
          "October",
          "November",
          "December",
        ],
      },
      {
        "title": "Opposite Words",
        "sub": "Learn Opposites",
        "icon": "↔️",
        "color": Colors.orange,
        "content": [
          "Big - Small",
          "Hot - Cold",
          "Happy - Sad",
          "Up - Down",
          "Fast - Slow",
          "Open - Close",
          "Tall - Short",
          "Day - Night",
        ],
      },
      {
        "title": "Fruits Names",
        "sub": "Healthy Fruits",
        "icon": "🍓",
        "color": Colors.red,
        "content": [
          "🍎 Apple",
          "🍌 Banana",
          "🍇 Grapes",
          "🍊 Orange",
          "🥭 Mango",
          "🍉 Watermelon",
          "🍍 Pineapple",
          "🍓 Strawberry",
        ],
      },
      {
        "title": "Vegetables Names",
        "sub": "Healthy Vegetables",
        "icon": "🥕",
        "color": Colors.green,
        "content": [
          "🥕 Carrot",
          "🥦 Broccoli",
          "🥔 Potato",
          "🍅 Tomato",
          "🌽 Corn",
          "🥬 Cabbage",
          "🧅 Onion",
          "🧄 Garlic",
        ],
      },
    ],
    "GK": [
      {
        "title": "Body Parts",
        "sub": "Know your body",
        "icon": "🧒",
        "color": Colors.brown,
        "content": [
          "👁️ Eyes",
          "👂 Ears",
          "👃 Nose",
          "👄 Mouth",
          "✋ Hands",
          "🦶 Feet",
        ],
      },
      {
        "title": "Animals",
        "sub": "Wild & Pet Animals",
        "icon": "🦁",
        "color": Colors.deepOrange,
        "content": [
          "🦁 Lion",
          "🐯 Tiger",
          "🐘 Elephant",
          "🐒 Monkey",
          "🐶 Dog",
          "🐱 Cat",
        ],
      },
      {
        "title": "Fruits & Veggies",
        "sub": "Healthy food",
        "icon": "🍎",
        "color": Colors.lightGreen,
        "content": [
          "🍎 Apple",
          "🥭 Mango",
          "🍌 Banana",
          "🥦 Broccoli",
          "🥕 Carrot",
          "🥔 Potato",
        ],
      },
    ],
    "Hindi": [
      {
        "title": "Swar (स्वर)",
        "sub": "अ से अनार",
        "icon": "🕉️",
        "color": Colors.redAccent,
        "content": [
          "🍎 अ से अनार",
          "🥭 आ से आम",
          "🫚 इ से इमली",
          "🍬 ई से ईख",
          "🦉 उ से उल्लू",
          "🧶 ऊ से ऊन",
          "ऋ से ऋषि",
          "👠 ए से एड़ी",
          "👓 ऐ से ऐनक",
          "🪵 ओ से ओखली",
          "👩 औ से औरत",
          "🌙 अं से अंगूर",
          "🙏 अः (विसर्ग)",
        ],
      },
      {
        "title": "Vyanjan (व्यंजन)",
        "sub": "क से कबूतर",
        "icon": "✍️",
        "color": Colors.orangeAccent,
        "content": [
          "🪷 क से कमल",
          "🐰 ख से खरगोश",
          "🚗 ग से गाड़ी",
          "🏠 घ से घर",
          "🦁 ङ (कम प्रयोग)",
          "🥄 च से चम्मच",
          "☂️ छ से छाता",
          "🚢 ज से जहाज",
          "🏳️ झ से झंडा",
          "ञ (कम प्रयोग)",
          "🍅 ट से टमाटर",
          "🧊 ठ से ठंड",
          "डमरू ड से डमरू",
          "🛡 ढ से ढाल",
          "ण (कम प्रयोग)",
          "🧵 त से तराजू",
          "🛎 थ से थाली",
          "🚪 द से दरवाज़ा",
          "🏹 ध से धनुष",
          "💧 न से नल",
          "🪁 प से पतंग",
          "🪓 फ से फल",
          "⚽ ब से बल्ला",
          "🐻 भ से भालू",
          "🐟 म से मछली",
          "🧘 य से योग",
          "🚂 र से रेल",
          "🪔 ल से लालटेन",
          "🚐 व से वाहन",
          "🦁 श से शेर",
          "ष (कम प्रयोग)",
          "🌞 स से सूरज",
          "✋ ह से हाथ",
          "🪓 क्ष से क्षत्रिय",
          "🚦 त्र से त्रिशूल",
          "📚 ज्ञ से ज्ञान",
        ],
      },
    ],
    "Math": [
      {
        "title": "Numbers 1-100",
        "sub": "Let's Count!",
        "icon": "🔢",
        "color": Colors.greenAccent,
        "content": List.generate(100, (index) => "${index + 1}"),
      },
      {
        "title": "Number Names (1-20)",
        "sub": "Learn Number Names",
        "icon": "✏️",
        "color": Colors.orangeAccent,
        "content": [
          "1 - One",
          "2 - Two",
          "3 - Three",
          "4 - Four",
          "5 - Five",
          "6 - Six",
          "7 - Seven",
          "8 - Eight",
          "9 - Nine",
          "10 - Ten",
          "11 - Eleven",
          "12 - Twelve",
          "13 - Thirteen",
          "14 - Fourteen",
          "15 - Fifteen",
          "16 - Sixteen",
          "17 - Seventeen",
          "18 - Eighteen",
          "19 - Nineteen",
          "20 - Twenty",
        ],
      },
      {
        "title": "Tables (2-10)",
        "sub": "Multiplication Tables",
        "icon": "✖️",
        "color": Colors.indigoAccent,
        "content": List.generate(9, (i) {
          int table = i + 2;
          return List.generate(
            10,
            (j) => "$table x ${j + 1} = ${table * (j + 1)}",
          );
        }).expand((e) => e).toList(),
      },
      {
        "title": "Addition (Single Digit)",
        "sub": "Learn Addition",
        "icon": "➕",
        "color": Colors.blueAccent,
        "content": [
          "1 + 1 = 2",
          "2 + 3 = 5",
          "4 + 2 = 6",
          "5 + 3 = 8",
          "6 + 2 = 8",
          "7 + 1 = 8",
          "8 + 1 = 9",
          "9 + 0 = 9",
        ],
      },
      {
        "title": "Subtraction (Single Digit)",
        "sub": "Learn Subtraction",
        "icon": "➖",
        "color": Colors.redAccent,
        "content": [
          "2 - 1 = 1",
          "5 - 2 = 3",
          "6 - 3 = 3",
          "8 - 4 = 4",
          "9 - 5 = 4",
          "7 - 2 = 5",
          "10 - 6 = 4",
        ],
      },
      {
        "title": "Before & After Numbers",
        "sub": "Number Order",
        "icon": "↔️",
        "color": Colors.purpleAccent,
        "content": [
          "Before 5 = 4",
          "After 5 = 6",
          "Before 10 = 9",
          "After 10 = 11",
          "Before 20 = 19",
          "After 20 = 21",
        ],
      },
      {
        "title": "Counting Objects",
        "sub": "Count the Items",
        "icon": "🍎",
        "color": Colors.teal,
        "content": [
          "🍎🍎 = 2 Apples",
          "🍌🍌🍌 = 3 Bananas",
          "⭐⭐⭐⭐ = 4 Stars",
          "🐶🐶🐶🐶🐶 = 5 Dogs",
          "🍓🍓🍓🍓🍓🍓 = 6 Strawberries",
        ],
      },
    ],
  };
}
