import 'package:flutter/material.dart';

class LearningContent {
  // ── Category metadata for UI chips ────────────────────────
  static final Map<String, Map<String, dynamic>> categories = {
    'Hindi':   {'emoji': '🕉️', 'color': const Color(0xFFB71C1C)},
    'Science': {'emoji': '🔬', 'color': const Color(0xFF00838F)},
    'Stories': {'emoji': '📖', 'color': const Color(0xFF4527A0)},
    'ABC':     {'emoji': '🔤', 'color': const Color(0xFF1565C0)},
    'Math':    {'emoji': '🔢', 'color': const Color(0xFF2E7D32)},
    'Animals': {'emoji': '🐾', 'color': const Color(0xFFE65100)},
    'Poems':   {'emoji': '🎵', 'color': const Color(0xFF9C27B0)},
    'Colors':  {'emoji': '🎨', 'color': const Color(0xFFC2185B)},
  };

  static final Map<String, List<Map<String, dynamic>>> data = {
    // ═══════════════════════════════════════════════════════
    // 🎵 POEMS
    // ═══════════════════════════════════════════════════════
    'Poems': [
      {
        'title': 'Twinkle Twinkle',
        'sub': 'Classic Nursery Rhyme',
        'icon': '⭐',
        'color': const Color(0xFF7B1FA2),
        'type': 'poem',
        'content': [
          'Twinkle, twinkle, little star,',
          'How I wonder what you are!',
          'Up above the world so high,',
          'Like a diamond in the sky.',
          'When the blazing sun is gone,',
          'When he nothing shines upon,',
          'Then you show your little light,',
          'Twinkle, twinkle, through the night.',
        ],
      },
      {
        'title': 'Johnny Johnny',
        'sub': 'Funny Rhyme',
        'icon': '🍬',
        'color': const Color(0xFFE65100),
        'type': 'poem',
        'content': [
          'Johnny Johnny, yes papa?',
          'Eating sugar? No papa.',
          'Telling lies? No papa.',
          'Open your mouth. Ha ha ha!',
        ],
      },
      {
        'title': 'Baa Baa Black Sheep',
        'sub': 'Animal Rhyme',
        'icon': '🐑',
        'color': const Color(0xFF1565C0),
        'type': 'poem',
        'content': [
          'Baa, baa, black sheep,',
          'Have you any wool?',
          'Yes sir, yes sir,',
          'Three bags full!',
          'One for the master,',
          'One for the dame,',
          'And one for the little boy,',
          'Who lives down the lane.',
        ],
      },
      {
        'title': 'Humpty Dumpty',
        'sub': 'Story Rhyme',
        'icon': '🥚',
        'color': const Color(0xFFC62828),
        'type': 'poem',
        'content': [
          'Humpty Dumpty sat on a wall,',
          'Humpty Dumpty had a great fall,',
          'All the king\'s horses and all the king\'s men,',
          'Couldn\'t put Humpty together again.',
        ],
      },
      {
        'title': 'Rain Rain Go Away',
        'sub': 'Weather Rhyme',
        'icon': '🌧️',
        'color': const Color(0xFF00695C),
        'type': 'poem',
        'content': [
          'Rain rain go away,',
          'Come again another day,',
          'Little children want to play,',
          'Rain rain go away!',
        ],
      },
      {
        'title': 'Jack and Jill',
        'sub': 'Adventure Rhyme',
        'icon': '🪣',
        'color': const Color(0xFF1A237E),
        'type': 'poem',
        'content': [
          'Jack and Jill went up the hill,',
          'To fetch a pail of water,',
          'Jack fell down and broke his crown,',
          'And Jill came tumbling after.',
        ],
      },
      {
        'title': 'Old MacDonald',
        'sub': 'Animal Farm Song',
        'icon': '🐄',
        'color': const Color(0xFF4E342E),
        'type': 'poem',
        'content': [
          'Old MacDonald had a farm, E-I-E-I-O!',
          'And on that farm he had a cow, E-I-E-I-O!',
          'With a moo moo here, and a moo moo there,',
          'Here a moo, there a moo, everywhere a moo moo!',
          'Old MacDonald had a farm, E-I-E-I-O!',
        ],
      },
      {
        'title': 'Itsy Bitsy Spider',
        'sub': 'Action Rhyme',
        'icon': '🕷️',
        'color': const Color(0xFF37474F),
        'type': 'poem',
        'content': [
          'Itsy bitsy spider climbed up the water spout,',
          'Down came the rain and washed the spider out,',
          'Out came the sunshine and dried up all the rain,',
          'Itsy bitsy spider climbed up the spout again!',
        ],
      },
      {
        'title': 'Row Row Your Boat',
        'sub': 'Action Song',
        'icon': '🚣',
        'color': const Color(0xFF006064),
        'type': 'poem',
        'content': [
          'Row, row, row your boat,',
          'Gently down the stream,',
          'Merrily, merrily, merrily, merrily,',
          'Life is but a dream!',
        ],
      },
      {
        'title': 'One Two Buckle My Shoe',
        'sub': 'Counting Rhyme',
        'icon': '👟',
        'color': const Color(0xFF2E7D32),
        'type': 'poem',
        'content': [
          'One, two, buckle my shoe,',
          'Three, four, shut the door,',
          'Five, six, pick up sticks,',
          'Seven, eight, lay them straight,',
          'Nine, ten, a big fat hen!',
        ],
      },
      {
        'title': 'Chubby Cheeks',
        'sub': 'Cute Rhyme',
        'icon': '😊',
        'color': const Color(0xFFAD1457),
        'type': 'poem',
        'content': [
          'Chubby cheeks, dimple chin,',
          'Rosy lips, teeth within,',
          'Curly hair, very fair,',
          'Eyes are blue, lovely too!',
          'Teacher\'s pet, that is me,',
          'Can\'t you see? Can\'t you see!',
        ],
      },
      {
        'title': 'Mary Had a Little Lamb',
        'sub': 'Classic Rhyme',
        'icon': '🐏',
        'color': const Color(0xFF558B2F),
        'type': 'poem',
        'content': [
          'Mary had a little lamb,',
          'Its fleece was white as snow,',
          'And everywhere that Mary went,',
          'The lamb was sure to go!',
          'It followed her to school one day,',
          'Which was against the rule,',
          'It made the children laugh and play,',
          'To see a lamb at school!',
        ],
      },
    ],

    // ═══════════════════════════════════════════════════════
    // 🔤 ABC
    // ═══════════════════════════════════════════════════════
    'ABC': [
      {
        'title': 'Alphabets A-Z',
        'sub': 'A for Apple, B for Ball',
        'icon': '🔤',
        'color': const Color(0xFF1565C0),
        'type': 'card',
        'content': [
          '🍎 A — Apple', '🎈 B — Ball', '🐱 C — Cat',
          '🐕 D — Dog', '🐘 E — Elephant', '🐟 F — Fish',
          '🦒 G — Giraffe', '🏠 H — House', '🍦 I — Ice Cream',
          '🧃 J — Juice', '🪁 K — Kite', '🦁 L — Lion',
          '🥭 M — Mango', '🪺 N — Nest', '🍊 O — Orange',
          '🦜 P — Parrot', '👑 Q — Queen', '🐇 R — Rabbit',
          '⭐ S — Star', '🐯 T — Tiger', '☂️ U — Umbrella',
          '🚐 V — Van', '⌚ W — Watch', '🎄 X — Xmas Tree',
          '🛳️ Y — Yacht', '🦓 Z — Zebra',
        ],
      },
      {
        'title': 'Vowels — A E I O U',
        'sub': 'The 5 Magic Letters',
        'icon': '🅰️',
        'color': const Color(0xFF01579B),
        'type': 'card',
        'content': [
          '🍎 A — Apple, Ant, Arm',
          '🐣 E — Egg, Ear, Eagle',
          '🍦 I — Ice cream, Ink, Island',
          '🍊 O — Orange, Owl, Ocean',
          '☂️ U — Umbrella, Up, Under',
        ],
      },
      {
        'title': 'Number Names 1-20',
        'sub': 'Learn Number Words',
        'icon': '✏️',
        'color': const Color(0xFF0277BD),
        'type': 'card',
        'content': [
          '1 — One', '2 — Two', '3 — Three', '4 — Four',
          '5 — Five', '6 — Six', '7 — Seven', '8 — Eight',
          '9 — Nine', '10 — Ten', '11 — Eleven', '12 — Twelve',
          '13 — Thirteen', '14 — Fourteen', '15 — Fifteen',
          '16 — Sixteen', '17 — Seventeen', '18 — Eighteen',
          '19 — Nineteen', '20 — Twenty',
        ],
      },
      {
        'title': 'Action Words',
        'sub': 'Verbs — Move Your Body!',
        'icon': '🏃',
        'color': const Color(0xFF1976D2),
        'type': 'card',
        'content': [
          '🏃 Run', '🚶 Walk', '💃 Dance', '😴 Sleep',
          '📚 Read', '✍️ Write', '🎨 Draw', '🏊 Swim',
          '🗣️ Speak', '👀 Look', '👂 Listen', '🍽️ Eat',
          '🏋️ Jump', '😄 Laugh', '🤗 Hug', '🎵 Sing',
        ],
      },
      {
        'title': 'Fruits Names',
        'sub': 'Healthy & Delicious',
        'icon': '🍓',
        'color': const Color(0xFF283593),
        'type': 'card',
        'content': [
          '🍎 Apple', '🍌 Banana', '🍇 Grapes', '🍊 Orange',
          '🥭 Mango', '🍉 Watermelon', '🍍 Pineapple',
          '🍓 Strawberry', '🫐 Blueberry', '🍒 Cherry',
          '🥝 Kiwi', '🍑 Peach', '🍐 Pear', '🍋 Lemon',
        ],
      },
      {
        'title': 'Vegetables Names',
        'sub': 'Eat Your Veggies!',
        'icon': '🥕',
        'color': const Color(0xFF0D47A1),
        'type': 'card',
        'content': [
          '🥕 Carrot', '🥦 Broccoli', '🥔 Potato', '🍅 Tomato',
          '🌽 Corn', '🥬 Cabbage', '🧅 Onion', '🧄 Garlic',
          '🥒 Cucumber', '🫑 Capsicum', '🍆 Brinjal', '🥗 Spinach',
        ],
      },
      {
        'title': 'Opposite Words',
        'sub': 'Learn the Opposites',
        'icon': '↔️',
        'color': const Color(0xFF1A237E),
        'type': 'card',
        'content': [
          '⬆️ Big  ↔  Small ⬇️',
          '🔥 Hot  ↔  Cold ❄️',
          '😄 Happy  ↔  Sad 😢',
          '⬆️ Up  ↔  Down ⬇️',
          '🏎️ Fast  ↔  Slow 🐢',
          '🚪 Open  ↔  Close 🔒',
          '📏 Tall  ↔  Short 📐',
          '☀️ Day  ↔  Night 🌙',
          '⬛ Black  ↔  White ⬜',
          '🌊 Wet  ↔  Dry 🏜️',
          '👴 Old  ↔  New 🆕',
          '💪 Strong  ↔  Weak 🤕',
        ],
      },
      {
        'title': 'Days & Months',
        'sub': 'Days of Week + 12 Months',
        'icon': '📅',
        'color': const Color(0xFF303F9F),
        'type': 'card',
        'content': [
          '1️⃣ Sunday', '2️⃣ Monday', '3️⃣ Tuesday',
          '4️⃣ Wednesday', '5️⃣ Thursday', '6️⃣ Friday',
          '7️⃣ Saturday',
          '🌸 January', '❤️ February', '🌱 March',
          '🌈 April', '🌺 May', '☀️ June',
          '⛱️ July', '🍂 August', '🍁 September',
          '🎃 October', '🍂 November', '❄️ December',
        ],
      },
    ],

    // ═══════════════════════════════════════════════════════
    // 🔢 MATH
    // ═══════════════════════════════════════════════════════
    'Math': [
      {
        'title': 'Count 1 to 20',
        'sub': 'Let\'s Count Together!',
        'icon': '🔢',
        'color': const Color(0xFF2E7D32),
        'type': 'card',
        'content': List.generate(20, (i) {
          final emojis = ['1️⃣','2️⃣','3️⃣','4️⃣','5️⃣','6️⃣','7️⃣','8️⃣','9️⃣','🔟',
                          '1️⃣1️⃣','1️⃣2️⃣','1️⃣3️⃣','1️⃣4️⃣','1️⃣5️⃣','1️⃣6️⃣','1️⃣7️⃣','1️⃣8️⃣','1️⃣9️⃣','2️⃣0️⃣'];
          return '${emojis[i]} — ${i + 1}';
        }),
      },
      {
        'title': 'Count 21 to 50',
        'sub': 'Keep Counting!',
        'icon': '🔟',
        'color': const Color(0xFF388E3C),
        'type': 'card',
        'content': List.generate(30, (i) => '${i + 21}'),
      },
      {
        'title': 'Count 51 to 100',
        'sub': 'You\'re a Math Star!',
        'icon': '💯',
        'color': const Color(0xFF1B5E20),
        'type': 'card',
        'content': List.generate(50, (i) => '${i + 51}'),
      },
      {
        'title': 'Addition',
        'sub': 'Adding Numbers Together',
        'icon': '➕',
        'color': const Color(0xFF43A047),
        'type': 'card',
        'content': [
          '🍎 1 + 1 = 2',  '🍌 2 + 3 = 5',  '⭐ 3 + 4 = 7',
          '🎈 4 + 2 = 6',  '🏀 5 + 5 = 10', '🎵 6 + 3 = 9',
          '🌟 7 + 2 = 9',  '🌈 8 + 4 = 12', '🦋 9 + 6 = 15',
          '🎯 10 + 5 = 15','🍕 11 + 4 = 15','🚀 12 + 8 = 20',
        ],
      },
      {
        'title': 'Subtraction',
        'sub': 'Taking Away Numbers',
        'icon': '➖',
        'color': const Color(0xFF2E7D32),
        'type': 'card',
        'content': [
          '🍎 5 - 2 = 3',   '🌙 8 - 3 = 5',  '🎈 10 - 4 = 6',
          '⭐ 7 - 2 = 5',   '🐶 9 - 5 = 4',  '🍌 12 - 6 = 6',
          '🌈 15 - 7 = 8',  '🏀 20 - 9 = 11','🦋 18 - 5 = 13',
        ],
      },
      {
        'title': 'Tables 2, 3, 4, 5',
        'sub': 'Multiplication Tables',
        'icon': '✖️',
        'color': const Color(0xFF388E3C),
        'type': 'card',
        'content': [
          ...List.generate(10, (j) => '2 × ${j + 1} = ${2 * (j + 1)}'),
          ...List.generate(10, (j) => '3 × ${j + 1} = ${3 * (j + 1)}'),
          ...List.generate(10, (j) => '4 × ${j + 1} = ${4 * (j + 1)}'),
          ...List.generate(10, (j) => '5 × ${j + 1} = ${5 * (j + 1)}'),
        ],
      },
      {
        'title': 'Even & Odd Numbers',
        'sub': 'Pairs or Not?',
        'icon': '🔄',
        'color': const Color(0xFF1B5E20),
        'type': 'card',
        'content': [
          '✅ Even: 2, 4, 6, 8, 10',
          '❌ Odd: 1, 3, 5, 7, 9',
          '✅ 2 is Even', '❌ 3 is Odd',
          '✅ 4 is Even', '❌ 5 is Odd',
          '✅ 6 is Even', '❌ 7 is Odd',
          '✅ 8 is Even', '❌ 9 is Odd',
          '✅ 10 is Even', '❌ 11 is Odd',
          '✅ 12 is Even', '❌ 13 is Odd',
        ],
      },
      {
        'title': 'Shapes & Sides',
        'sub': 'Count the Sides!',
        'icon': '🔷',
        'color': const Color(0xFF33691E),
        'type': 'card',
        'content': [
          '⚪ Circle — 0 sides',
          '🔺 Triangle — 3 sides',
          '⬜ Square — 4 equal sides',
          '▭ Rectangle — 4 sides',
          '⬠ Pentagon — 5 sides',
          '⬡ Hexagon — 6 sides',
          '⭐ Star — 10 points',
          '💎 Diamond — 4 sides',
          '🥚 Oval — 0 sides, like an egg',
        ],
      },
    ],

    // ═══════════════════════════════════════════════════════
    // 🐾 ANIMALS
    // ═══════════════════════════════════════════════════════
    'Animals': [
      {
        'title': 'Pet Animals',
        'sub': 'Animals at Home',
        'icon': '🐶',
        'color': const Color(0xFFE65100),
        'type': 'card',
        'content': [
          '🐶 Dog — Woof Woof!',
          '🐱 Cat — Meow Meow!',
          '🐟 Fish — Swims in water',
          '🐰 Rabbit — Hops fast!',
          '🐹 Hamster — Small & fluffy',
          '🦜 Parrot — Can talk!',
          '🐢 Turtle — Slow but steady',
          '🐠 Goldfish — Orange & pretty',
          '🐓 Hen — Cluck cluck!',
          '🐇 Bunny — Loves carrots',
        ],
      },
      {
        'title': 'Wild Animals',
        'sub': 'Animals in the Jungle',
        'icon': '🦁',
        'color': const Color(0xFFBF360C),
        'type': 'card',
        'content': [
          '🦁 Lion — King of the jungle!',
          '🐯 Tiger — Has orange stripes',
          '🐘 Elephant — Largest land animal',
          '🦒 Giraffe — Tallest animal',
          '🦓 Zebra — Black and white stripes',
          '🐆 Cheetah — Fastest animal!',
          '🐻 Bear — Loves honey & fish',
          '🦊 Fox — Very clever!',
          '🐺 Wolf — Lives in packs',
          '🦏 Rhino — Has a big horn',
          '🦛 Hippo — Loves water',
          '🐒 Monkey — Loves bananas',
        ],
      },
      {
        'title': 'Sea Animals',
        'sub': 'Under the Ocean!',
        'icon': '🐬',
        'color': const Color(0xFFD84315),
        'type': 'card',
        'content': [
          '🐬 Dolphin — Very smart!',
          '🦈 Shark — Big teeth!',
          '🐙 Octopus — 8 arms!',
          '🐟 Fish — Swims in schools',
          '🦞 Lobster — Red & tasty',
          '🦀 Crab — Walks sideways',
          '🐠 Tropical Fish — Colorful!',
          '🐋 Whale — Biggest animal',
          '🦭 Seal — Claps flippers',
          '🐡 Pufferfish — Puffs up big!',
          '🦑 Squid — Shoots black ink',
          '🐚 Snail — Carries its home',
        ],
      },
      {
        'title': 'Birds',
        'sub': 'Flying Creatures',
        'icon': '🦅',
        'color': const Color(0xFFE64A19),
        'type': 'card',
        'content': [
          '🦅 Eagle — Great hunter!',
          '🦜 Parrot — Green & clever',
          '🐧 Penguin — Cannot fly!',
          '🦚 Peacock — Beautiful feathers',
          '🦆 Duck — Quack quack!',
          '🦉 Owl — Wise, sees at night',
          '🐓 Rooster — Wakes us up!',
          '🦢 Swan — Graceful & white',
          '🐦 Sparrow — Tiny & fast',
          '🦩 Flamingo — Pink & stands tall',
        ],
      },
      {
        'title': 'Farm Animals',
        'sub': 'Animals on the Farm',
        'icon': '🐄',
        'color': const Color(0xFFF4511E),
        'type': 'card',
        'content': [
          '🐄 Cow — Gives us milk 🥛',
          '🐑 Sheep — Gives us wool 🧶',
          '🐖 Pig — Oink oink!',
          '🐔 Chicken — Gives us eggs 🥚',
          '🐴 Horse — Neigh neigh!',
          '🐐 Goat — Gives us milk too!',
          '🦆 Duck — Lives near ponds',
          '🐇 Rabbit — Soft & fluffy',
          '🐓 Rooster — Wakes up at sunrise',
          '🐕 Dog — Guards the farm',
        ],
      },
    ],

    // ═══════════════════════════════════════════════════════
    // 🕉️ HINDI
    // ═══════════════════════════════════════════════════════
    'Hindi': [
      {
        'title': 'Swar — स्वर',
        'sub': 'अ से अः तक',
        'icon': '🕉️',
        'color': const Color(0xFFB71C1C),
        'type': 'card',
        'content': [
          '🍎 अ se अनार — Aur English mein kahate hain Pomegranate',
          '🥭 आ se आम — Aur English mein kahate hain Mango',
          '🫚 इ se इमली — Aur English mein kahate hain Tamarind',
          '🍬 ई se ईख — Aur English mein kahate hain Sugarcane',
          '🦉 उ se उल्लू — Aur English mein kahate hain Owl',
          '🧶 ऊ se ऊन — Aur English mein kahate hain Wool',
          '🌺 ऋ se ऋषि — Aur English mein kahate hain Sage',
          '👠 ए se एड़ी — Aur English mein kahate hain Heel',
          '👓 ऐ se ऐनक — Aur English mein kahate hain Glasses',
          '🪵 ओ se ओखली — Aur English mein kahate hain Mortar',
          '👩 औ se औरत — Aur English mein kahate hain Woman',
          '🍇 अं se अंगूर — Aur English mein kahate hain Grapes',
          '🙏 अः — Visarg, Aur English mein kahate hain Visarga',
        ],
      },
      {
        'title': 'Vyanjan — व्यंजन',
        'sub': 'क से ज्ञ तक',
        'icon': '✍️',
        'color': const Color(0xFFC62828),
        'type': 'card',
        'content': [
          '🪷 क se कमल — Aur English mein kahate hain Lotus',
          '🐰 ख se खरगोश — Aur English mein kahate hain Rabbit',
          '🚗 ग se गाड़ी — Aur English mein kahate hain Car',
          '🏠 घ se घर — Aur English mein kahate hain Home',
          '🥄 च se चम्मच — Aur English mein kahate hain Spoon',
          '☂️ छ se छाता — Aur English mein kahate hain Umbrella',
          '🚢 ज se जहाज — Aur English mein kahate hain Ship',
          '🏳️ झ se झंडा — Aur English mein kahate hain Flag',
          '🍅 ट se टमाटर — Aur English mein kahate hain Tomato',
          '🧊 ठ se ठंड — Aur English mein kahate hain Cold',
          '🛡️ ढ se ढाल — Aur English mein kahate hain Shield',
          '🧵 त se तराजू — Aur English mein kahate hain Scale',
          '🚪 द se दरवाज़ा — Aur English mein kahate hain Door',
          '🏹 ध se धनुष — Aur English mein kahate hain Bow',
          '💧 न se नल — Aur English mein kahate hain Tap',
          '🪁 प se पतंग — Aur English mein kahate hain Kite',
          '🍎 फ se फल — Aur English mein kahate hain Fruit',
          '⚽ ब se बल — Aur English mein kahate hain Ball',
          '🐻 भ se भालू — Aur English mein kahate hain Bear',
          '🐟 म se मछली — Aur English mein kahate hain Fish',
          '🚂 र se रेल — Aur English mein kahate hain Train',
          '🪔 ल se लालटेन — Aur English mein kahate hain Lantern',
          '🦁 श se शेर — Aur English mein kahate hain Lion',
          '🌞 स se सूरज — Aur English mein kahate hain Sun',
          '✋ ह se हाथ — Aur English mein kahate hain Hand',
          '📚 ज्ञ se ज्ञान — Aur English mein kahate hain Knowledge',
        ],
      },
      {
        'title': 'Hindi Numbers 1–10',
        'sub': 'एक से दस तक',
        'icon': '🔢',
        'color': const Color(0xFFB71C1C),
        'type': 'card',
        'content': [
          '1️⃣ एक matlab One — Aur English mein kahate hain One',
          '2️⃣ दो matlab Two — Aur English mein kahate hain Two',
          '3️⃣ तीन matlab Three — Aur English mein kahate hain Three',
          '4️⃣ चार matlab Four — Aur English mein kahate hain Four',
          '5️⃣ पाँच matlab Five — Aur English mein kahate hain Five',
          '6️⃣ छः matlab Six — Aur English mein kahate hain Six',
          '7️⃣ सात matlab Seven — Aur English mein kahate hain Seven',
          '8️⃣ आठ matlab Eight — Aur English mein kahate hain Eight',
          '9️⃣ नौ matlab Nine — Aur English mein kahate hain Nine',
          '🔟 दस matlab Ten — Aur English mein kahate hain Ten',
        ],
      },
      {
        'title': 'Simple Hindi Words',
        'sub': 'रोज़ काम आने वाले शब्द',
        'icon': '📝',
        'color': const Color(0xFF880E4F),
        'type': 'card',
        'content': [
          '🏠 घर — Aur English mein kahate hain Home',
          '🌞 सूरज — Aur English mein kahate hain Sun',
          '🌙 चाँद — Aur English mein kahate hain Moon',
          '💧 पानी — Aur English mein kahate hain Water',
          '🍎 फल — Aur English mein kahate hain Fruit',
          '🌸 फूल — Aur English mein kahate hain Flower',
          '🐄 गाय — Aur English mein kahate hain Cow',
          '🐶 कुत्ता — Aur English mein kahate hain Dog',
          '👶 बच्चा — Aur English mein kahate hain Child',
          '👨‍👩‍👧 परिवार — Aur English mein kahate hain Family',
          '📚 किताब — Aur English mein kahate hain Book',
          '✏️ कलम — Aur English mein kahate hain Pen',
        ],
      },
    ],

    // ═══════════════════════════════════════════════════════
    // 🔬 SCIENCE
    // ═══════════════════════════════════════════════════════
    'Science': [
      {
        'title': 'My Body Parts',
        'sub': 'Know Your Body!',
        'icon': '🧒',
        'color': const Color(0xFF00838F),
        'type': 'card',
        'content': [
          '👁️ Eyes — We see with eyes',
          '👂 Ears — We hear with ears',
          '👃 Nose — We smell with nose',
          '👄 Mouth — We eat & speak',
          '🦷 Teeth — We chew food',
          '✋ Hands — We work with hands',
          '🦶 Feet — We walk with feet',
          '🫀 Heart — It pumps blood',
          '🧠 Brain — Controls everything!',
          '🦴 Bones — Hold our body up',
          '💪 Muscles — Make us strong',
          '🫁 Lungs — We breathe with lungs',
        ],
      },
      {
        'title': 'Planets in Space',
        'sub': 'Our Solar System',
        'icon': '🪐',
        'color': const Color(0xFF006064),
        'type': 'card',
        'content': [
          '☀️ Sun — The star at center',
          '🌑 Mercury — Closest to Sun, very hot',
          '💛 Venus — Brightest planet',
          '🌍 Earth — Our home planet!',
          '🔴 Mars — The Red planet',
          '🟠 Jupiter — Biggest planet!',
          '🪐 Saturn — Has beautiful rings',
          '🔵 Uranus — Rolls on its side',
          '💙 Neptune — Farthest from Sun',
        ],
      },
      {
        'title': 'Weather Types',
        'sub': 'What\'s the Weather?',
        'icon': '🌤️',
        'color': const Color(0xFF00695C),
        'type': 'card',
        'content': [
          '☀️ Sunny — Warm and bright!',
          '🌧️ Rainy — Water falls from clouds',
          '⛅ Cloudy — Clouds cover the sun',
          '❄️ Snowy — Cold white snow falls',
          '🌬️ Windy — Strong air blows',
          '⛈️ Stormy — Thunder and lightning!',
          '🌈 Rainbow — After the rain',
          '🌫️ Foggy — Hard to see far',
          '🌩️ Thunder — Rumble in the sky',
        ],
      },
      {
        'title': 'Four Seasons',
        'sub': 'Spring, Summer, Fall, Winter',
        'icon': '🌸',
        'color': const Color(0xFF004D40),
        'type': 'card',
        'content': [
          '🌸 Spring — Flowers bloom, birds sing',
          '☀️ Summer — Hot days, play outside!',
          '🍂 Autumn — Leaves fall, orange & red',
          '❄️ Winter — Cold, snow, warm clothes',
          '🌱 Spring brings new plants',
          '🏖️ Summer is best for swimming',
          '🎃 Autumn has Halloween!',
          '⛄ Winter brings snowmen & Christmas',
        ],
      },
      {
        'title': 'Plants & Trees',
        'sub': 'The Green World Around Us',
        'icon': '🌱',
        'color': const Color(0xFF1B5E20),
        'type': 'card',
        'content': [
          '🌱 Seed — Start of a plant',
          '🌿 Root — Drinks water underground',
          '🍂 Leaf — Makes food from sunlight',
          '🌸 Flower — Makes seeds & is pretty',
          '🍎 Fruit — Grows from flowers',
          '🌲 Tree — Gives us oxygen!',
          '☀️ Plants need: Sunlight',
          '💧 Plants need: Water',
          '🌍 Plants need: Soil',
          '🌬️ Plants give us: Fresh air',
        ],
      },
      {
        'title': 'Food Groups',
        'sub': 'Eat Healthy, Stay Strong!',
        'icon': '🥗',
        'color': const Color(0xFF2E7D32),
        'type': 'card',
        'content': [
          '🥦 Vegetables — Make us healthy',
          '🍎 Fruits — Give us vitamins',
          '🌾 Grains — Give us energy',
          '🧀 Dairy — Makes bones strong',
          '🍗 Protein — Builds muscles',
          '💧 Water — Most important!',
          '🍫 Less sweets — Stay healthy',
          '🥤 Less soda — Drink water instead',
        ],
      },
    ],

    // ═══════════════════════════════════════════════════════
    // 📖 STORIES
    // ═══════════════════════════════════════════════════════
    'Stories': [
      {
        'title': 'The Thirsty Crow',
        'sub': 'Use your brain!',
        'icon': '🐦',
        'color': const Color(0xFF4527A0),
        'type': 'story',
        'content': [
          '🌞 Once upon a time, a crow was very thirsty on a hot day.',
          '🔍 The crow flew here and there looking for water.',
          '🫙 Finally, it found a pot with a little water at the bottom.',
          '😔 The crow\'s beak could not reach the water inside the pot.',
          '💡 The clever crow had a great idea!',
          '🪨 The crow picked up small stones and dropped them into the pot.',
          '📈 The water level slowly rose up higher and higher.',
          '💧 At last, the crow could drink the cool water!',
          '💡 Moral: Where there is a will, there is a way!',
        ],
      },
      {
        'title': 'The Lion & the Mouse',
        'sub': 'Small can help big!',
        'icon': '🦁',
        'color': const Color(0xFF6A1B9A),
        'type': 'story',
        'content': [
          '🌳 Once, a lion was sleeping under a big tree in the jungle.',
          '🐭 A tiny mouse was playing nearby and accidentally ran over the lion!',
          '😡 The lion woke up, caught the mouse, and was about to eat it.',
          '🙏 "Please spare me! I will help you one day!" said the mouse.',
          '😄 The lion laughed at this and let the mouse go.',
          '🕸️ One day, the lion got trapped in a hunter\'s net.',
          '🦁 The lion roared loudly for help.',
          '🐭 The little mouse heard the lion and came running!',
          '✂️ The mouse chewed the ropes of the net and set the lion free!',
          '💡 Moral: A small act of kindness can save a life!',
        ],
      },
      {
        'title': 'The Tortoise & the Hare',
        'sub': 'Slow and steady wins!',
        'icon': '🐢',
        'color': const Color(0xFF1A237E),
        'type': 'story',
        'content': [
          '🐇 A hare always laughed at the slow tortoise.',
          '"You walk so slowly! I am much faster!" said the hare.',
          '🐢 The tortoise smiled and said, "Let\'s have a race!"',
          '🏁 The next day, the race began in the forest.',
          '🏃 The hare ran very fast and was far ahead quickly.',
          '😴 The hare thought, "I will rest here. The tortoise is so slow!"',
          '🐢 The tortoise kept walking slowly but never stopped.',
          '🏆 When the hare woke up, the tortoise had already won the race!',
          '💡 Moral: Slow and steady wins the race!',
        ],
      },
      {
        'title': 'The Golden Egg',
        'sub': 'Don\'t be greedy!',
        'icon': '🥚',
        'color': const Color(0xFF4A148C),
        'type': 'story',
        'content': [
          '🧑‍🌾 Once upon a time, a farmer had a special goose.',
          '🥚 Every morning, the goose would lay one golden egg!',
          '💰 The farmer sold the golden eggs and became rich.',
          '😤 But one day, the farmer became very greedy.',
          '💭 He thought, "If I cut open the goose, I can get ALL the eggs at once!"',
          '😢 The foolish farmer cut open the goose.',
          '😱 But he found no golden eggs inside! The goose was just a normal goose.',
          '💡 Moral: Never be greedy! Be satisfied with what you have.',
        ],
      },
      {
        'title': 'The Fox & the Grapes',
        'sub': 'Don\'t make excuses!',
        'icon': '🦊',
        'color': const Color(0xFF311B92),
        'type': 'story',
        'content': [
          '🦊 One day, a hungry fox spotted a bunch of juicy grapes on a vine.',
          '🍇 The grapes were high up and looked sweet and delicious!',
          '🦘 The fox jumped again and again, but could not reach them.',
          '😤 After trying many times, the fox was very tired.',
          '😤 "Those grapes are probably sour anyway!" said the fox.',
          '🚶 The fox walked away pretending not to care.',
          '💡 Moral: Never make excuses for things you can\'t get!',
        ],
      },
      {
        'title': 'The Ant & the Grasshopper',
        'sub': 'Work hard today!',
        'icon': '🐜',
        'color': const Color(0xFF1A237E),
        'type': 'story',
        'content': [
          '☀️ All summer long, the ant worked very hard collecting food.',
          '🦗 The grasshopper played music and danced all day instead.',
          '"Why do you work so hard? Come dance with me!" said the grasshopper.',
          '🐜 "I am saving food for winter," said the wise ant.',
          '❄️ When winter came, snow covered everything.',
          '🦗 The grasshopper had no food and was very hungry and cold.',
          '🐜 The kind ant shared some food with the grasshopper.',
          '💡 Moral: Always work hard today and save for tomorrow!',
        ],
      },
    ],

    // ═══════════════════════════════════════════════════════
    // 🎨 COLORS
    // ═══════════════════════════════════════════════════════
    'Colors': [
      {
        'title': 'Rainbow Colors',
        'sub': 'ROYGBIV — 7 Colors',
        'icon': '🌈',
        'color': const Color(0xFFC2185B),
        'type': 'card',
        'content': [
          '🔴 Red — Color of apples & roses',
          '🟠 Orange — Color of oranges!',
          '🟡 Yellow — Bright like the sun',
          '🟢 Green — Color of leaves & grass',
          '🔵 Blue — Color of the sky & sea',
          '🔷 Indigo — Deep blue-purple',
          '🟣 Violet — Lightest purple',
          '🌈 Together they make a RAINBOW!',
        ],
      },
      {
        'title': 'Colors Everywhere',
        'sub': 'Colors in Our World',
        'icon': '🎨',
        'color': const Color(0xFFAD1457),
        'type': 'card',
        'content': [
          '⚪ White — Snow, milk, clouds',
          '⚫ Black — Night sky, charcoal',
          '🟤 Brown — Chocolate, mud, wood',
          '🌸 Pink — Roses, flamingos',
          '🩵 Light Blue — Morning sky',
          '💚 Light Green — Fresh leaves',
          '🧡 Peach — Sunset colors',
          '💛 Gold — Stars, trophies, coins',
          '💜 Purple — Grapes, lavender',
          '❤️ Dark Red — Cherries, blood',
        ],
      },
      {
        'title': '2D Shapes',
        'sub': 'Flat Shapes Around Us',
        'icon': '🔷',
        'color': const Color(0xFF880E4F),
        'type': 'card',
        'content': [
          '⚪ Circle — Ball, sun, wheel',
          '⬜ Square — Window, tile',
          '🔺 Triangle — Pizza slice, tent',
          '▭ Rectangle — Door, book, phone',
          '💎 Diamond — Kite, diamond gem',
          '⭐ Star — Night sky',
          '❤️ Heart — Valentine\'s day!',
          '🥚 Oval — Egg, leaf',
          '⬠ Pentagon — US building shape',
          '⬡ Hexagon — Honeybee cells!',
        ],
      },
      {
        'title': 'Mixing Colors',
        'sub': 'What Colors Make Together!',
        'icon': '🖌️',
        'color': const Color(0xFFB71C1C),
        'type': 'card',
        'content': [
          '🔴 Red + 🔵 Blue = 🟣 Purple',
          '🔴 Red + 🟡 Yellow = 🟠 Orange',
          '🔵 Blue + 🟡 Yellow = 🟢 Green',
          '⚪ White + ❤️ Red = 🌸 Pink',
          '⚪ White + ⚫ Black = 🩶 Gray',
          '🟡 Yellow + ⚫ Black = 🟤 Dark Yellow',
          '🔴 Red + 🟠 Orange = 🧡 Warm Orange',
          '🔵 Blue + 🟢 Green = 🩵 Teal',
        ],
      },
    ],
  };
}
